CSharp Playwright - manual flow
browserstack/csharp-playwright-browserstack pull request #3
Opened 2023-08-07 15:50 UTC by kamal-kaur04

2023-08-14 09:23 UTC, 07souravkunda requested changes

2023-08-14 09:23 UTC, 07souravkunda commented on CSharp-Playwright-BrowserStack/BrowserStackNUnitTest.cs
> +            //string path = Path.Combine("/Users/kamalpreet/Documents/fork-samples/csharp-playwright-browserstack/CSharp-Playwright-BrowserStack/config.json");
remove local path

2023-08-14 09:27 UTC, 07souravkunda requested changes

2023-08-14 09:27 UTC, 07souravkunda commented on CSharp-Playwright-BrowserStack/BrowserStackNUnitTest.cs
> +            //string path = Path.Combine("/Users/kamalpreet/Documents/fork-samples/csharp-playwright-browserstack/CSharp-Playwright-BrowserStack/config.json");
```suggestion

```

2023-08-14 10:47 UTC, 07souravkunda approved these changes

2023-08-14 10:59 UTC, pranavj1001 approved these changes

2023-08-16 06:22 UTC, agrawalsaurabhs approved these changes

2023-08-16 14:04 UTC, merged